version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
    user: "${UID:-1000}:${GID:-1000}"
    container_name: senior-hcosta
    volumes:
      - .:/var/www/senior-hcosta
      - ./docker/supervisord/supervisord.conf:/etc/supervisor/supervisord.conf
    depends_on:
      - postgres
      - mongo
      - rabbitmq
      - redis
    networks:
      - senior-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "${APP_PORT}:80"
    volumes:
      - .:/var/www/senior-hcosta
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - senior-network

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    networks:
      - senior-network

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongodata:/data/db
    networks:
      - senior-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_WEB_PORT}:15672"
    networks:
      - senior-network

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - senior-network

volumes:
  pgdata:
  mongodata:

networks:
  senior-network:
    driver: bridge
